<template>
    <div class="mt-1">
        <div class="card p-0">
            <div class="row p-2">
                <div class="col-xl-6 p-md-5 p-4 border-end">
                    <div class="text-center">
                        <img src="/image/refer-and-earn/refer-and-earn.png" alt="Refer and Earn" width="340px"
                            class="img-fluid" />
                    </div>
                    <div class="mt-4">
                        <div class="text-quaternary-color fs16 fw500 pt-2">Refer and Earn</div>
                        <div class="text-secondary-color fs14 fw400 pt-2">Unlock a rewarding opportunity by referring
                            friends to join Alice Blue as partners! With our Refer and Earn program, you can build a
                            steady side income in just a few simple steps.</div>
                    </div>
                    <div class="mt-4">
                        <div class="d-flex align-items-center">
                            <img src="/image/refer-and-earn/refer-a-friend.png" alt="Step 1" width="24px"
                                height="24px" />
                            <div class="text-quaternary-color fs16 fw500 pt-1 ps-2">Refer a Friend</div>
                        </div>
                        <div class="text-secondary-color fs14 fw400 pt-2">Invite friends or colleagues to become
                            partners with Alice Blue. They’ll gain access to exciting benefits and a robust platform to
                            grow their business.</div>
                    </div>
                    <div class="mt-3">
                        <div class="d-flex align-items-center">
                            <img src="/image/refer-and-earn/mutual-growth.png" alt="Step 1" width="24px"
                                height="24px" />
                            <div class="text-quaternary-color fs16 fw500 pt-1 ps-2">Mutual Growth & Shared Earnings
                            </div>
                        </div>
                        <div class="text-secondary-color fs14 fw400 pt-2">When your friend generates business, they earn
                            60% of the revenue, while Alice Blue receives 40% to continue expanding our services.</div>
                    </div>
                    <div class="mt-3">
                        <div class="d-flex align-items-center">
                            <img src="/image/refer-and-earn/earn-commission.png" alt="Step 1" width="24px"
                                height="24px" />
                            <div class="text-quaternary-color fs16 fw500 pt-1 ps-2">Earn commission on partner’s sucess
                            </div>
                        </div>
                        <div class="text-secondary-color fs14 fw400 pt-2">You earn a 10% commission on Alice Blue’s 40%
                            share of the net income generated by your referred partner. The more they grow, the more you
                            earn!</div>
                    </div>
                    <div class="mt-4">
                        <div class="text-quaternary-color fs16 fw500 pt-2">Example Scenario : </div>
                        <div class="text-secondary-color fs14 fw400 pt-2 lh-lg">Your referred partner generates Rs
                            50,000<br>Alice Blue’s net Income (40% share): Rs 20,000<br>Your 10% commission : Rs 2,000
                        </div>
                    </div>
                </div>
                <div class="col-xl-6 position-relative d-flex justify-content-center align-items-center">
                    <img src="/image/refer-and-earn/re-right.png" alt="Refer and Earn"
                        class="d-xl-block d-none img-right" />
                    <img src="/image/refer-and-earn/re-left.png" alt="Refer and Earn"
                        class="d-xl-block d-none img-bottom" />
                    <div class="card re-form p-md-4 p-2 my-xl-0 my-4">
                        <div class="card-body">
                            <form @submit.prevent="handleSubmit">
                                <div class="mb-3">
                                    <div class="position-relative">
                                        <div class="form-control-text">
                                            <label class="fs14 text-muted">Full Name</label>
                                            <input type="text" maxlength="30" @blur="validateName" @input="sanitizeName"
                                                v-model="form.name" class="fs14 mt-1 custom-input"
                                                placeholder="Enter the Full Name">
                                            <ErrorMessage :class="'text-start form-text fs12 text-danger'"
                                                :message="errors.name" />
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <div class="position-relative">
                                        <div class="form-control-text">
                                            <label class="fs14 text-muted">Email ID</label>
                                            <input type="email" maxlength="50" @blur="validateEmail"
                                                @input="sanitizeEmail" v-model="form.email"
                                                class="fs14 mt-1 custom-input" placeholder="Enter the Email ID">
                                            <ErrorMessage :class="'text-start form-text fs12 text-danger'"
                                                :message="errors.email" />
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <div class="position-relative">
                                        <div class="form-control-text">
                                            <label class="fs14 text-muted">Mobile Number</label>
                                            <input type="text" maxlength="10" @blur="validatePhone"
                                                v-model="form.mobile"
                                                oninput="this.value = this.value.replace(/[^0-9]/g, '');"
                                                class="fs14 mt-1 custom-input" placeholder="Enter the Mobile Number">
                                            <ErrorMessage :class="'text-start form-text fs12 text-danger'"
                                                :message="errors.mobile" />
                                        </div>
                                    </div>
                                </div>
                                <div class="text-center pt-3">
                                    <ButtonPrimary label="Refer A Partner" :disabled="loading" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref, reactive, onMounted, watch, nextTick, computed } from "vue";
import ErrorMessage from "../../../components/ErrorMessage.vue";
import ButtonPrimary from "../../../components/button/ButtonPrimary.vue"
import { useAuthStore } from '@/stores/authStore';
import { showErrorToast, showSuccessToast } from "../../../js/toast";
import { accountService } from "../../../services/account/account.service";

const authStore = useAuthStore();
const adminDetails = ref({});

const loading = ref(false);

const form = reactive({
    name: "",
    email: "",
    mobile: "",
});

const errors = reactive({
    name: "",
    email: "",
    mobile: "",
    message: ""
});

onMounted(() => {
    adminDetails.value = authStore.adminDetails;
});

const validatePhone = () => {
    const mobileRegex = /^[6-9]\d{9}$/;
    const repeatRegex = /(.)\1{7,}/;
    if (!form.mobile) {
        errors.mobile = "Mobile number is required.";
        loading.value = false;
    } else if (!mobileRegex.test(form.mobile)) {
        errors.mobile = "Mobile number must start with 6, 7, 8, or 9 and be 10 digits.";
        loading.value = false;
    } else if (repeatRegex.test(form.mobile)) {
        errors.mobile = "Mobile number must not have the same digit repeated more than 7 times.";
        loading.value = false;
    } else {
        errors.mobile = "";
    }
};

const sanitizeEmail = (event) => {
    const clean = event.target.value.replace(/[^a-zA-Z0-9@._-]/g, '');
    form.email = clean;
};

const validateEmail = () => {
    if (!form.email) {
        errors.email = "Email ID is required.";
        loading.value = false;
    } else {
        errors.email = "";
    }
};


const sanitizeName = (event) => {
    const clean = event.target.value.replace(/[^a-zA-Z ]/g, '');
    form.name = clean;
};

const validateName = () => {
    if (!form.name) {
        errors.name = "Full name is required.";
        loading.value = false;
    } else {
        errors.name = "";
    }
};

const handleSubmit = async () => {
    validateName();
    validateEmail();
    validatePhone();
    if (!errors.name && !errors.email && !errors.mobile) {
        loading.value = true;
        const formData = {
            referredID: adminDetails.value.RemCode,
            leadName: form.name.toUpperCase(),
            leadEmail: form.email.toUpperCase(),
            leadmobile: form.mobile,
            leadState: "karnataka"
        };
        try {
            const response = await accountService.referAndEarn(formData);
            if (response.data?.isSuccess) {
                if (response.data.data.isCreated) {
                    showSuccessToast(response.data.message);
                    close();
                    loading.value = false;
                } else {
                    showErrorToast(response.data.message);
                    errors.message = response.data.message;
                    loading.value = false;
                }
            } else {
                errors.message = response.data?.message ;
                loading.value = false;
            }
        } catch (error) {
            errors.message = err.response.data?.message || 'Something went wrong, please try again later.';
            loading.value = false;
        }
    } else {
        loading.value = false;
    }
};

const close = () => {
    form.name = "";
    form.email = "";
    form.mobile = "";
    errors.name = "";
    errors.email = "";
    errors.mobile = "";
    errors.message = "";
    loading.value = false;
};
</script>



<style scoped>
.img-right {
    position: absolute;
    top: 0;
    right: 12px;
    border-radius: 12px;
    width: 200px !important;
}

.img-bottom {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 200px !important;
}

.re-form {
    width: 100% !important;
    max-width: 450px !important;
    box-shadow: rgba(9, 30, 66, 0.25) 0px 4px 8px -2px, rgba(9, 30, 66, 0.08) 0px 0px 0px 1px !important;
}
</style>